Training/2021.11 E1 - Advanced Tasking
AdaCore/training_material pull request #159
Opened 2022-01-19 17:07 UTC by leogermond

2022-04-11 19:37 UTC, frank-at-adacore requested changes

2022-04-11 19:37 UTC, frank-at-adacore commented on courses/fundamentals_of_ada/adv_240_tasking.rst
> +- Absolute: Blocks until a given :ada:`Calendar.Time` or :ada:`Real_Time.Time`
until no earlier than

2022-04-11 19:37 UTC, frank-at-adacore commented on courses/fundamentals_of_ada/adv_240_tasking.rst
> + * Instanciate an **anonymous** task (or protected) type
Instantiate

2022-04-19 07:33 UTC, leogermond commented on courses/fundamentals_of_ada/adv_240_tasking.rst
> +- Absolute: Blocks until a given :ada:`Calendar.Time` or :ada:`Real_Time.Time`
Done

2022-04-19 07:34 UTC, leogermond commented on courses/fundamentals_of_ada/adv_240_tasking.rst
> + * Instanciate an **anonymous** task (or protected) type
Done

2022-04-19 12:37 UTC, frank-at-adacore approved these changes

2022-04-19 12:52 UTC, merged