Advanced Type: Quiz
AdaCore/training_material pull request #185
Opened 2022-04-19 14:52 UTC by leogermond

- adv subtypes: quiz
- lint 030

2022-04-19 15:17 UTC, frank-at-adacore submitted a review, later dismissed
General comment about the quizzes:
When doing these online, I use a webex/meet poll that I have stored in a file (so I don't have to populate the poll every time). Previous quizzes always had four possible answers, and one possible solution, so I could always use the same file.
As I'm not sure how much "advanced" we'll be doing online, not sure it's a big deal here, but it is something to consider

2022-04-19 15:17 UTC, frank-at-adacore commented on courses/fundamentals_of_ada/adv_030_basic_types.rst
> +Which statements are correct?
Same as previous comment

2022-04-19 15:17 UTC, frank-at-adacore commented on courses/fundamentals_of_ada/adv_030_basic_types.rst
> +Which of the following propositions are true?
In the phrasing of this and the previous, the student can't tell if there should be only 1 answer, or 1 or more answers

2022-04-20 07:32 UTC, leogermond commented
Not sure I understand the webex file stuff, I guess it's possible to have several of them pre-saved? Don't hesitate to share this kind of resources in the future, I'm interested.

2022-04-20 07:33 UTC, leogermond commented on courses/fundamentals_of_ada/adv_030_basic_types.rst
> +What is the result of :ada:`T2'Base`?
Maybe type then? Range in that context would be understood as the Ada reserved word, but that's not the question.

2022-04-20 07:35 UTC, leogermond commented on courses/fundamentals_of_ada/adv_030_basic_types.rst
> +Quiz
Right, fixed it

2022-04-25 12:38 UTC, frank-at-adacore commented on courses/fundamentals_of_ada/adv_030_basic_types.rst
> +What is the result of :ada:`T2'Base`?
1) Range of T2 is 1..9, range of T1 is 0..10 - that's what I mean
2) 'Base gives you the range of the _number of bits_ used, so answer A is actually correct (try writing a simple program with    "ada.text_io.put_line(t2'base'first'image);"

2022-04-25 12:40 UTC, frank-at-adacore commented
> Not sure I understand the webex file stuff, I guess it's possible to have several of them pre-saved? Don't hesitate to share this kind of resources in the future, I'm interested.

Good idea. I have a Webex file, I'll create a Google Meet version and push them to the repository

2022-04-26 13:01 UTC, frank-at-adacore requested changes

2022-04-26 13:01 UTC, frank-at-adacore commented on courses/fundamentals_of_ada/adv_030_basic_types.rst
> +What is the :ada:`type` of :ada:`T2'Base`?
This quiz looks duplicated? (First occurrence has wrong answer)

2022-04-26 13:01 UTC, frank-at-adacore commented on courses/fundamentals_of_ada/adv_030_basic_types.rst
> +Which statements are legal?
should be "statement(s) is(are)"

2022-04-28 12:51 UTC, leogermond commented on courses/fundamentals_of_ada/adv_030_basic_types.rst
> +What is the result of :ada:`T2'Base`?
Ah I see, let's remove that question then, it is in the chapter about base types

2022-04-28 14:35 UTC, frank-at-adacore approved these changes

2022-04-28 14:52 UTC, merged