Tool gnat project facility
AdaCore/training_material pull request #189
Opened 2022-04-27 14:07 UTC by frank-at-adacore

2022-04-29 12:18 UTC, leogermond requested changes

2022-05-03 15:45 UTC, frank-at-adacore commented on courses/gnat_project_facility/020_building_with_gprbuild.rst
> +    * - -P *<project file>*
Done

2022-05-03 15:50 UTC, frank-at-adacore commented on courses/gnat_project_facility/030_project_properties.rst
> ++ Must be at least one **immediate** source file
First bullet was (kind of) - made it more explicit

2022-05-03 15:54 UTC, frank-at-adacore commented on courses/gnat_project_facility/030_project_properties.rst
> +    + Child's object directory contains output for source not already compiled in parent
rephrased

2022-05-03 16:19 UTC, frank-at-adacore commented on courses/gnat_project_facility/040_structuring_your_application.rst
> +               Foo.Compiler'Default_Switches & "-gnatwa";
added a note (it's in the GPR UG)

2022-05-03 18:02 UTC, frank-at-adacore commented on courses/gnat_project_facility/040_structuring_your_application.rst
> +  + Source in project A refers to source in project B, and source in project B refers to source in project A
Done

2022-05-04 14:54 UTC, frank-at-adacore commented on courses/gnat_project_facility/labs/source/020_building_with_gprbuild/queens.adb
> +with Ada.Command_Line;
All set

2022-05-04 15:33 UTC, leogermond submitted a review, later dismissed

2022-05-12 17:50 UTC, merged