Static analysis labs
AdaCore/training_material pull request #211
Opened 2022-05-30 16:58 UTC by frank-at-adacore

Content of course has not changed, just split into multiple modules so I could add the two labs
Labs are brand new and need to be reviewed

2022-06-03 18:17 UTC, rchoch approved these changes

2022-06-06 12:00 UTC, leogermond requested changes

2022-06-06 12:00 UTC, leogermond commented on courses/static_analysis_via_compiler/labs/source/src/cruise.adb
> +      elsif Time_Collision_Front < 0.0
the chaining of if/elsif is hard to follow, and some conditions seem redundant

2023-03-31 18:17 UTC, frank-at-adacore commented
Removing until needed

2023-03-31 18:17 UTC, closed without merging